//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedbacks
    {
        public int Fid { get; set; }
        public Nullable<int> Custid { get; set; }
        public Nullable<int> Pid { get; set; }
        public Nullable<int> First { get; set; }
        public Nullable<int> Second { get; set; }
        public Nullable<int> Third { get; set; }
        public Nullable<int> Fourth { get; set; }
        public Nullable<int> Fifth { get; set; }
        public Nullable<int> Sixth { get; set; }
        public Nullable<int> Seventh { get; set; }
        public string Addition { get; set; }
        public string Deletion { get; set; }
        public string Comments { get; set; }
        public Nullable<double> Avg { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
    }
}
